[package]
name = "infrastructure"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
strum.workspace = true

[lints]
workspace = true
