name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Formatting
        run: cargo fmt --verbose --check
      - name: Linting
        run: cargo clippy --verbose --all-targets --all-features
      - name: Build
        run: cargo build --verbose
      - name: Tests
        run: cargo test --verbose
